[project]
name = "playwright-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.7",
    "playwright>=1.51.0",
    "pytest>=8.3.5",
    "pytest-django>=4.10.0",
    "pytest-playwright>=0.7.0",
]
